### ISSUE TITLE
Missing .env

### ISSUE THREAD

**Issue by JoraJora** [iwpnd/weightwhat#3]
Hi, 

Amazing work in this repo, do you have .env in the project ?

**Comment by iwpnd** [comment]
Hi @JoraJora, and thanks.
Yes I do use an .env file. You can check [here](https://github.com/iwpnd/weightwhat/blob/master/weightwhat/backend/app/core/config.py) to see what is in it and how it is used.

**Comment by JoraJora** [comment]
thanks @iwpnd for the answer.

**Comment by drorata** [comment]
Great stuff indeed! Thanks.

I'm afraid the link is not helpful enough for me :( Can you post a template of the `.env`?
