### ISSUE TITLE
No weights found

### ISSUE THREAD

**Issue by Mohammadabd** [iwpnd/weightwhat#5]
I need to add `weights.csv` to Postgres database but the backend image misses pandas. I tried installing pandas on backend image (alpine) but since it need to build wheels first it takes so long and did not finish installing pandas so I could run `upload_weights.csv`. Any suggestion on how to get initial weights into Postgres? 

pip install pandas hangs on _Building wheel for pandas (PEP 517) ... -_

**Thanks**

**Comment by iwpnd** [comment]
You can also just use psycopg2 and iterate over the weights you want to upload
